"""
Mock Prometheus adapter.
Reads from sample_data.json (generated by data/generator.py).
To swap in real Prometheus, replace this adapter with prometheus_adapter.py —
the application layer and API layer are unchanged (hexagonal ports).
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from ...domain.models import (
    DataPoint, DashboardSummary, ErrorBudget, Incident, SLAObligation,
    SLI, SLIType, SLO, ServiceMetrics, Severity, Status,
)
from ...domain.ports import IMetricsRepository

_DATA_PATH = Path(__file__).parent.parent.parent.parent / "sample_data.json"

_SEVERITY_MAP = {
    "low": Severity.LOW,
    "medium": Severity.MEDIUM,
    "high": Severity.HIGH,
    "critical": Severity.CRITICAL,
}

_SLI_DESCRIPTIONS = {
    "availability": "Percentage of time the service successfully handled requests (non-5xx / total requests). Measured over the SLO window.",
    "latency_p99": "99th-percentile end-to-end response time in milliseconds. 1 in 100 requests is slower than this value.",
    "latency_p95": "95th-percentile response time. Good proxy for tail latency without outlier sensitivity.",
    "error_rate": "Percentage of requests returning HTTP 5xx (server errors). Excludes client 4xx errors.",
    "throughput": "Requests per second successfully served. A drop here often precedes availability degradation.",
}


class MockMetricsAdapter(IMetricsRepository):
    def __init__(self):
        with open(_DATA_PATH) as f:
            self._data = json.load(f)
        self._services_raw = self._data["services"]
        self._incidents_raw = self._data["incidents"]
        self._sla_raw = self._data["sla_obligations"]

    def _parse_slo(self, svc_name: str, svc_raw: dict) -> list[SLO]:
        cur = svc_raw["current"]
        targets = svc_raw["slo_targets"]
        burns = svc_raw["burn_rates"]
        budget_raw = svc_raw["error_budget"]
        window = 30

        eb = ErrorBudget(
            total_minutes=budget_raw["total_minutes"],
            consumed_minutes=budget_raw["consumed_minutes"],
            burn_rate_1h=burns["1h"],
            burn_rate_6h=burns["6h"],
            burn_rate_24h=burns["24h"],
        )

        slos = []

        # --- Availability SLO ---
        sli_avail = SLI(
            name="Availability",
            type=SLIType.AVAILABILITY,
            unit="%",
            description=_SLI_DESCRIPTIONS["availability"],
            current_value=cur["availability"],
            target_value=targets["availability"],
        )
        slos.append(SLO(
            id=f"{svc_name}_availability",
            name="Availability",
            service_name=svc_name,
            sli=sli_avail,
            window_days=window,
            error_budget=eb,
            description=f"Service must be available ≥ {targets['availability']}% of the time over any rolling 30-day window.",
        ))

        # --- Latency p99 SLO ---
        sli_lat = SLI(
            name="Latency p99",
            type=SLIType.LATENCY_P99,
            unit="ms",
            description=_SLI_DESCRIPTIONS["latency_p99"],
            current_value=cur["latency_p99"],
            target_value=targets["latency_p99"],
        )
        slos.append(SLO(
            id=f"{svc_name}_latency_p99",
            name="Latency p99",
            service_name=svc_name,
            sli=sli_lat,
            window_days=window,
            error_budget=eb,
            description=f"99th-percentile latency must stay below {targets['latency_p99']} ms.",
        ))

        # --- Error Rate SLO ---
        sli_er = SLI(
            name="Error Rate",
            type=SLIType.ERROR_RATE,
            unit="%",
            description=_SLI_DESCRIPTIONS["error_rate"],
            current_value=cur["error_rate"],
            target_value=targets["error_rate"],
        )
        slos.append(SLO(
            id=f"{svc_name}_error_rate",
            name="Error Rate",
            service_name=svc_name,
            sli=sli_er,
            window_days=window,
            error_budget=eb,
            description=f"5xx error rate must remain below {targets['error_rate']}%.",
        ))

        return slos

    def _parse_incidents(self, service_name: Optional[str] = None) -> list[Incident]:
        result = []
        for inc in self._incidents_raw:
            if service_name and inc["service"] != service_name:
                continue
            started = datetime.fromisoformat(inc["started_at"])
            resolved = (
                datetime.fromisoformat(inc["resolved_at"]) if inc.get("resolved_at") else None
            )
            result.append(Incident(
                id=inc["id"],
                service_name=inc["service"],
                title=inc["title"],
                severity=_SEVERITY_MAP.get(inc["severity"], Severity.MEDIUM),
                started_at=started,
                resolved_at=resolved,
                affected_slis=inc.get("affected_slis", []),
                impact_description=inc.get("impact_description", ""),
                root_cause=inc.get("root_cause"),
            ))
        return result

    def _build_service(self, svc_name: str) -> ServiceMetrics:
        svc_raw = self._services_raw[svc_name]
        meta = svc_raw["meta"]
        slos = self._parse_slo(svc_name, svc_raw)
        incidents = self._parse_incidents(svc_name)
        avail_30d = svc_raw["current"]["availability"]
        score = min(100, max(0, (avail_30d - 98) / 2 * 100))

        return ServiceMetrics(
            name=svc_name,
            display_name=meta["display_name"],
            description=meta["description"],
            team=meta["team"],
            slos=slos,
            incidents=incidents,
            mttr_minutes=svc_raw["mttr_minutes"],
            mtbf_hours=svc_raw["mtbf_hours"],
            reliability_score=round(score, 1),
        )

    async def get_dashboard_summary(self) -> DashboardSummary:
        services = [self._build_service(n) for n in self._services_raw]
        incidents = self._parse_incidents()
        active = [i for i in incidents if i.is_active]
        last_30 = [
            i for i in incidents
            if (datetime.now(timezone.utc) - i.started_at.replace(tzinfo=timezone.utc)).days <= 30
        ]
        resolved = [i for i in incidents if i.resolved_at]
        mean_ttr = (
            sum(i.duration_minutes for i in resolved if i.duration_minutes) / max(len(resolved), 1)
        )

        all_avails = [
            svc_data["current"]["availability"]
            for svc_data in self._services_raw.values()
        ]
        overall = sum(all_avails) / len(all_avails)
        statuses = [s.overall_status for s in services]
        if any(s == Status.BREACHED for s in statuses):
            overall_status = Status.BREACHED
        elif any(s == Status.AT_RISK for s in statuses):
            overall_status = Status.AT_RISK
        else:
            overall_status = Status.HEALTHY

        return DashboardSummary(
            overall_availability=round(overall, 4),
            overall_status=overall_status,
            services=services,
            sla_obligations=await self.get_sla_obligations(),
            active_incidents=active,
            total_incidents_30d=len(last_30),
            mean_ttd_minutes=18.4,
            mean_ttr_minutes=mean_ttr,
            as_of=datetime.now(timezone.utc),
        )

    async def get_service_metrics(self, service_name: str) -> Optional[ServiceMetrics]:
        if service_name not in self._services_raw:
            return None
        return self._build_service(service_name)

    async def get_availability_timeseries(
        self, service_name: str, start: datetime, end: datetime, step_hours: int = 24
    ) -> list[DataPoint]:
        if service_name not in self._services_raw:
            return []
        svc = self._services_raw[service_name]
        daily = svc["daily"]
        result = []
        for d in daily:
            dt = datetime.fromisoformat(d["date"] + "T00:00:00+00:00")
            if start <= dt <= end:
                result.append(DataPoint(timestamp=dt, value=d["availability"]))
        return result

    async def get_error_budget_timeseries(
        self, service_name: str, start: datetime, end: datetime
    ) -> list[DataPoint]:
        if service_name not in self._services_raw:
            return []
        svc = self._services_raw[service_name]
        budget_ts = svc["error_budget"]["timeseries"]
        result = []
        for d in budget_ts:
            dt = datetime.fromisoformat(d["date"] + "T00:00:00+00:00")
            if start <= dt <= end:
                result.append(DataPoint(timestamp=dt, value=d["budget_remaining_pct"]))
        return result

    async def get_sla_obligations(self) -> list[SLAObligation]:
        all_svc = list(self._services_raw.values())
        last_30_avail = [
            sum(d["availability"] for d in svc["daily"][-30:]) / 30
            for svc in all_svc
        ]
        overall_mtd = sum(last_30_avail) / len(last_30_avail)
        result = []
        for ob in self._sla_raw:
            result.append(SLAObligation(
                tier=ob["tier"],
                target_availability=ob["target_availability"],
                mtd_availability=ob["mtd_availability"],
                credit_threshold=ob["credit_threshold"],
                credit_pct=ob["credit_pct"],
                incident_response_minutes=ob["incident_response_minutes"],
            ))
        return result

    async def get_incidents(
        self,
        service_name: Optional[str] = None,
        limit: int = 50,
        severity: Optional[str] = None,
    ) -> list[Incident]:
        incidents = self._parse_incidents(service_name)
        if severity:
            incidents = [i for i in incidents if i.severity.value == severity]
        return incidents[:limit]

    async def get_heatmap_data(self, service_name: str, days: int = 30) -> list[dict]:
        if service_name not in self._services_raw:
            return []
        svc = self._services_raw[service_name]
        daily = svc["daily"][-days:]
        target = svc["slo_targets"]["availability"]
        result = []
        for d in daily:
            avail = d["availability"]
            if avail >= target:
                status = "healthy"
            elif avail >= target - 0.5:
                status = "at_risk"
            elif avail >= target - 2.0:
                status = "degraded"
            else:
                status = "outage"
            result.append({"date": d["date"], "availability": avail, "status": status})
        return result

    def get_raw_service_data(self, service_name: str) -> dict:
        return self._services_raw.get(service_name, {})
